[package]
name = "local_vector_database"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.21"
rayon = "1.9"
serde_json = "1.0"
rand = "0.9.0"
bytemuck = "1.21.0"
